### ISSUE TITLE
Weird result when testing GRIN using the testGrin.Sh file

### ISSUE THREAD

**Issue by thipple505** [sullivanka/GRIN#3]
Hello, I hope you are doing well.
I have been trying to set up GRIN and I keep getting this weird error/result when running the bash testGRIN.sh file. Do you know what might be causing this? Thank you for the help i appreciate it! I am in an anaconda navigator environment (Named GRIN). I followed the github instructions on how to set it up. I am using R version 4.1.3 and the anaconda r- precompiled packages for the R packages (i.e. r-igraph, r-doparallel). I also have R-tools V4.0 installed and added to the path for compiling the two other github repos that are used (RandomWalkRestartMH and KneeArrower). I am on Windows 11 if that makes a difference. Thank you for the help! Attached is a screenshot of the error I have been getting.
![GRIN_Error_043024](https://github.com/sullivanka/GRIN/assets/85587310/d1a1fa67-3a0d-4a75-9ee4-0e2584aced67)

**Comment by sullivanka** [comment]
Hello, it appears you may not have dplyr installed due to the pipe function not being found. Also please be sure you have git-lfs installed so that you can properly clone the multiplex network.
